name: animation_helpers
description: Facilitators to develop flutter animations
version: 1.0.3
homepage: https://flutterando.com.br
git: https://github.com/davidsdearaujo/animation_helpers
repository: https://github.com/davidsdearaujo/animation_helpers

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: